// infrastructure/react/components/player.tsx
import { PlayerEnumeration } from "@application/domain/enumerations/player"
import { Fragment } from "react";

export interface PlayerPropsInterface {
  player: PlayerEnumeration
}

export const Player = ({ player }) => {
  if (player === PlayerEnumeration.Circle) {
    return <Fragment>O</Fragment>
  }

  if (player === PlayerEnumeration.Cross) {
    return <Fragment>X</Fragment>
  }

  return null;
}

// infrastructure/vue/components/player.vue
<template>
  <div v-if="player === PlayerEnumeration.Cross">X</div>
  <div v-else-if="player === PlayerEnumeration.Circle">O</div>
  <div v-else></div>
</template>

<script lang="ts" setup>
import { PlayerEnumeration } from "@application/domain/enumerations/player";

const { player } = defineProps({
  player: String
});
</script>
