// infrastructure/vue/components/player.vue
<template>
  <div v-if="player === PlayerEnumeration.Cross">X</div>
  <div v-else-if="player === PlayerEnumeration.Circle">O</div>
  <div v-else></div>
</template>

<script lang="ts" setup>
import { PlayerEnumeration } from "@application/domain/enumerations/player";

const { player } = defineProps({
  player: String
});
</script>

// infrastructure/preact/src/components/player.tsx
import { Fragment } from "preact";
import { PlayerEnumeration } from "@application/domain/enumerations/player";

export const Player = ({ player }: { player: PlayerEnumeration }) => {
    if (player === PlayerEnumeration.Circle) {
        return (
            <Fragment>
                O
            </Fragment>
        )
    }

    if (player === PlayerEnumeration.Cross) {
        return (
            <Fragment>
                X
            </Fragment>
        )
    }

    return null;
}
